Ros2 collision fix
blackcoffeerobotics/bcr_bot pull request #24
Opened 2024-03-09 04:01 UTC by ANGELOANTU7

### Description

Removed Collision tag of traction_wheel in ros2

### Issue - Collision geometry that protrides out of the robot mesh #23 

![Screenshot from 2024-03-09 09-31-11](https://github.com/blackcoffeerobotics/bcr_bot/assets/94218410/e2c91b57-e94a-4118-8438-8448967ffc18)

2024-03-12 06:01 UTC, D-1shu commented
@ANGELOANTU7, could you please address the following points:

1. I am unable to observe the collisions being fixed Instead they are removed all together. I've followed these steps to verify the collisions. 
    a. Execute `ros2 launch bcr_bot gazebo.launch.py`.
    b. Execute `ros2 launch bcr_bot rviz.launch.py`.

2. After resolving the issue, squash the commits into a single commit and pull request should thoroughly explain the changes made. For future PRs kindly adhere to the instructions provided [here](https://gitlab.com/bcrllp/processes/development/-/blob/master/version-control-and-code-review.md?ref_type=heads) for version control and code review.

2024-03-13 16:24 UTC, ANGELOANTU7 commented
edit made

2024-03-15 17:28 UTC, D-1shu commented
Both these launch file results in error
a. `ros2 launch bcr_bot gazebo.launch.py`
b.  `ros2 launch bcr_bot gz.launch.py`
```
[ERROR] [launch]: Caught exception in launch (see debug for traceback): executed command failed. Command: xacro /home/devanshu/bcr_bot_antu/install/bcr_bot/share/bcr_bot/urdf/bcr_bot.xacro camera_enabled:=True stereo_camera_enabled:=False two_d_lidar_enabled:=True sim_gazebo:=true odometry_source:=world robot_namespace:=
Captured stderr output: XML parsing error: not well-formed (invalid token): line 52, column 1
when processing file: /home/devanshu/bcr_bot_antu/install/bcr_bot/share/bcr_bot/urdf/macros.xacro
included from: /home/devanshu/bcr_bot_antu/install/bcr_bot/share/bcr_bot/urdf/bcr_bot.xacro

Check that:
 - Your XML is well-formed
 - You have the xacro xmlns declaration: xmlns:xacro="http://www.ros.org/wiki/xacro"

```

2024-03-16 03:41 UTC, ANGELOANTU7 commented
resolved the issue

2024-03-27 10:54 UTC, D-1shu reviewed
LGTM!

2024-03-27 11:09 UTC, ggupta9777 requested changes

2024-03-27 11:09 UTC, ggupta9777 commented on urdf/bcr_bot.xacro
> +    <xacro:traction_wheel cardinality="middle" dexterity="left" origin_x="0" origin_y="${traction_track_width/2.75}" origin_z="-${chassis_height/2+2*trolley_wheel_radius+eps-traction_wheel_radius}"/>
@ANGELOANTU7  Why have you divided this by 2.75? This is an arbitrary choice

2024-03-27 16:07 UTC, closed without merging